name = "MeanSquaredDisplacement"
uuid = "1d9466cf-f50a-49b4-a9ad-ff74efd7c117"
authors = ["Riccardo Foffi <riccardo.foffi@protonmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
